version: '3'
services:
  menu_serv:
    build:
      context: ./menu_service
    ports:
      - "5001:5001"

  order_serv:
    build:
      context: ./order_service
    ports:
      - "5002:5002"
    depends_on:
      - menu_serv
      
  gateway:
    build:
      context: ./gateway
    ports:
      - "3000:3000"
    depends_on:
      - menu_serv
      - order_serv
